[package]
name = "nara_tooling_egui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
egui.workspace = true
nara_reflect.workspace = true
nara_scene.workspace = true
nara_tooling.workspace = true

[dev-dependencies]
nara_diagnostic.workspace = true
