[package]
name = "nara_image"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
image.workspace = true
nara_asset.workspace = true
serde = { workspace = true, optional = true }

[features]
default = []
serde = ["dep:serde", "nara_asset/serde"]
