[package]
name = "nara_sprite_render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bevy_ecs.workspace = true
nara_app.workspace = true
nara_asset.workspace = true
nara_core.workspace = true
nara_ecs.workspace = true
nara_image.workspace = true
nara_render.workspace = true
nara_sprite.workspace = true
nara_tilemap.workspace = true
nara_transform.workspace = true
