[package]
name = "nara_ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bevy_ecs.workspace = true
nara_app.workspace = true
nara_asset.workspace = true
nara_core.workspace = true
nara_ecs.workspace = true
nara_hierarchy.workspace = true
nara_image.workspace = true
nara_input.workspace = true
nara_material.workspace = true
nara_reflect.workspace = true
nara_render.workspace = true
serde = { workspace = true, optional = true }

[features]
default = []
serde = [
    "dep:serde",
    "nara_asset/serde",
    "nara_core/serde",
    "nara_image/serde",
    "nara_material/serde",
    "nara_render/serde",
]
