[package]
name = "nara_render_wgpu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bevy_ecs.workspace = true
bytemuck = { workspace = true, optional = true }
nara_app.workspace = true
nara_asset = { workspace = true, optional = true }
nara_ecs.workspace = true
nara_image = { workspace = true, optional = true }
nara_material = { workspace = true, optional = true }
nara_render.workspace = true
nara_sprite_render = { workspace = true, optional = true }
nara_ui_render = { workspace = true, optional = true }
nara_window.workspace = true
pollster.workspace = true
thiserror.workspace = true
wgpu.workspace = true

[dev-dependencies]
nara_core.workspace = true
nara_hierarchy.workspace = true
nara_reflect.workspace = true
nara_transform.workspace = true
nara_ui.workspace = true
raw-window-handle.workspace = true

[features]
default = []
sprite-submitter = [
    "dep:bytemuck",
    "dep:nara_asset",
    "dep:nara_image",
    "dep:nara_material",
    "dep:nara_sprite_render",
]
ui-submitter = [
    "dep:bytemuck",
    "dep:nara_asset",
    "dep:nara_image",
    "dep:nara_material",
    "dep:nara_ui_render",
]
