[package]
name = "nara_render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bevy_ecs.workspace = true
nara_app.workspace = true
nara_asset.workspace = true
nara_core.workspace = true
nara_ecs.workspace = true
nara_reflect.workspace = true
nara_transform.workspace = true
nara_window.workspace = true
serde = { workspace = true, optional = true }
thiserror.workspace = true

[features]
default = []
serde = ["dep:serde", "nara_asset/serde", "nara_core/serde", "nara_window/serde"]
