[package]
name = "nara_winit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
nara_app.workspace = true
nara_core.workspace = true
nara_ecs.workspace = true
nara_input.workspace = true
nara_window.workspace = true
winit.workspace = true

[dev-dependencies]
raw-window-handle.workspace = true
