[package]
name = "nara_asset_watch"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bevy_ecs.workspace = true
nara_app.workspace = true
nara_asset.workspace = true
nara_ecs.workspace = true
notify.workspace = true

[dev-dependencies]
nara_tasks.workspace = true

[features]
default = []
