[package]
name = "nara_diagnostic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bevy_ecs.workspace = true
nara_ecs.workspace = true
serde = { workspace = true, optional = true }
tracing.workspace = true

[features]
default = []
serde = ["dep:serde"]
